#!/usr/bin/env python3
# -*- coding: utf-8 -*-
""" For JSON Imports

Supporting script for Mnemonica App

The main purpose is as a seperate dictionary repository for stacks & gifs. At
the moment it's probably overkill but I wanted to learn a bit more about JSON.

Also if we start adding images - either discreptions or links to URLs it is much tider
to store those in a seperate file than in cluttering the main app interface.

"""
# %%

import json

# %% STACKS

# Stacks is a dictionary where each key is a stack
# stacks themselves are lists of dictionaries (useful for converting to dfs)
# to add a new stack, copy the 'blank' stack fill in the cards and run this script
# running the script will save the json file
stacks = {
        
    'tamariz':[
        {'posn':1,  'card':'4C', 'loci':1 , 'image':''},
        {'posn':2,  'card':'2H', 'loci':2 , 'image':''},
        {'posn':3,  'card':'7D', 'loci':3 , 'image':''},
        {'posn':4,  'card':'3C', 'loci':4 , 'image':''},
        {'posn':5,  'card':'4H', 'loci':5 , 'image':''},
        {'posn':6,  'card':'6D', 'loci':6 , 'image':''},
        {'posn':7,  'card':'AS', 'loci':7 , 'image':''},
        {'posn':8,  'card':'5H', 'loci':8 , 'image':''},
        {'posn':9,  'card':'9S', 'loci':9 , 'image':''},
        {'posn':10, 'card':'2S', 'loci':10 , 'image':''},
        {'posn':11, 'card':'QH', 'loci':11 , 'image':''},
        {'posn':12, 'card':'3D', 'loci':12 , 'image':''},
        {'posn':13, 'card':'QC', 'loci':13 , 'image':''},
        {'posn':14, 'card':'8H', 'loci':14 , 'image':''},
        {'posn':15, 'card':'6S', 'loci':15 , 'image':''},
        {'posn':16, 'card':'5S', 'loci':16 , 'image':''},
        {'posn':17, 'card':'9H', 'loci':17 , 'image':''},
        {'posn':18, 'card':'KC', 'loci':18 , 'image':''},
        {'posn':19, 'card':'2D', 'loci':19 , 'image':''},
        {'posn':20, 'card':'JH', 'loci':20 , 'image':''},
        {'posn':21, 'card':'3S', 'loci':21 , 'image':''},
        {'posn':22, 'card':'8S', 'loci':22 , 'image':''},
        {'posn':23, 'card':'6H', 'loci':23 , 'image':''},
        {'posn':24, 'card':'10C', 'loci':24 , 'image':''},
        {'posn':25, 'card':'5D', 'loci':25 , 'image':''},
        {'posn':26, 'card':'KD', 'loci':26 , 'image':''},
        {'posn':27, 'card':'2C', 'loci':27 , 'image':''},
        {'posn':28, 'card':'3H', 'loci':28 , 'image':''},
        {'posn':29, 'card':'8D', 'loci':29 , 'image':''},
        {'posn':30, 'card':'5C', 'loci':30 , 'image':''},
        {'posn':31, 'card':'KS', 'loci':31 , 'image':''},
        {'posn':32, 'card':'JD', 'loci':32 , 'image':''},
        {'posn':33, 'card':'8C', 'loci':33 , 'image':''},
        {'posn':34, 'card':'10S', 'loci':34 , 'image':''},
        {'posn':35, 'card':'KH', 'loci':35 , 'image':''},
        {'posn':36, 'card':'JC', 'loci':36 , 'image':''},
        {'posn':37, 'card':'7S', 'loci':37 , 'image':''},
        {'posn':38, 'card':'10H', 'loci':38 , 'image':''},
        {'posn':39, 'card':'AD', 'loci':39 , 'image':''},
        {'posn':40, 'card':'4S', 'loci':40 , 'image':''},
        {'posn':41, 'card':'7H', 'loci':41 , 'image':''},
        {'posn':42, 'card':'4D', 'loci':42 , 'image':''},
        {'posn':43, 'card':'AC', 'loci':43 , 'image':''},
        {'posn':44, 'card':'9C', 'loci':44 , 'image':''},
        {'posn':45, 'card':'JS', 'loci':45 , 'image':''},
        {'posn':46, 'card':'QD', 'loci':46 , 'image':''},
        {'posn':47, 'card':'7C', 'loci':47 , 'image':''},
        {'posn':48, 'card':'QS', 'loci':48 , 'image':''},
        {'posn':49, 'card':'10D', 'loci':49 , 'image':''},
        {'posn':50, 'card':'6C', 'loci':50 , 'image':''},
        {'posn':51, 'card':'AH', 'loci':51 , 'image':''},
        {'posn':52, 'card':'9D', 'loci':51 , 'image':''},
    ],

    'aronson':[
        {'posn':1,  'card':'JS', 'loci':1 , 'image':''},
        {'posn':2,  'card':'KC', 'loci':1 , 'image':''},
        {'posn':3,  'card':'5C', 'loci':2 , 'image':''},
        {'posn':4,  'card':'2H', 'loci':2 , 'image':''},
        {'posn':5,  'card':'9S', 'loci':3 , 'image':''},
        {'posn':6,  'card':'AS', 'loci':3 , 'image':''},
        {'posn':7,  'card':'3H', 'loci':4 , 'image':''},
        {'posn':8,  'card':'6C', 'loci':4 , 'image':''},
        {'posn':9,  'card':'8D', 'loci':5 , 'image':''},
        {'posn':10, 'card':'AC', 'loci':5 , 'image':''},
        {'posn':11, 'card':'10S', 'loci':6 , 'image':''},
        {'posn':12, 'card':'5H', 'loci':6 , 'image':''},
        {'posn':13, 'card':'2D', 'loci':7 , 'image':''},
        {'posn':14, 'card':'KD', 'loci':7 , 'image':''},
        {'posn':15, 'card':'7D', 'loci':8 , 'image':''},
        {'posn':16, 'card':'8C', 'loci':8 , 'image':''},
        {'posn':17, 'card':'3S', 'loci':9 , 'image':''},
        {'posn':18, 'card':'AD', 'loci':9 , 'image':''},
        {'posn':19, 'card':'7S', 'loci':10 , 'image':''},
        {'posn':20, 'card':'5S', 'loci':10 , 'image':''},
        {'posn':21, 'card':'QD', 'loci':11 , 'image':''},
        {'posn':22, 'card':'AH', 'loci':11 , 'image':''},
        {'posn':23, 'card':'8S', 'loci':12 , 'image':''},
        {'posn':24, 'card':'3D', 'loci':12 , 'image':''},
        {'posn':25, 'card':'7H', 'loci':13 , 'image':''},
        {'posn':26, 'card':'QH', 'loci':13 , 'image':''},
        {'posn':27, 'card':'5D', 'loci':14 , 'image':''},
        {'posn':28, 'card':'7C', 'loci':14 , 'image':''},
        {'posn':29, 'card':'4H', 'loci':15 , 'image':''},
        {'posn':30, 'card':'KH', 'loci':15 , 'image':''},
        {'posn':31, 'card':'4D', 'loci':16 , 'image':''},
        {'posn':32, 'card':'10D', 'loci':16 , 'image':''},
        {'posn':33, 'card':'JC', 'loci':17 , 'image':''},
        {'posn':34, 'card':'JH', 'loci':17 , 'image':''},
        {'posn':35, 'card':'10C', 'loci':18 , 'image':''},
        {'posn':36, 'card':'JD', 'loci':18 , 'image':''},
        {'posn':37, 'card':'4S', 'loci':19 , 'image':''},
        {'posn':38, 'card':'10H', 'loci':19 , 'image':''},
        {'posn':39, 'card':'6H', 'loci':20 , 'image':''},
        {'posn':40, 'card':'3C', 'loci':20 , 'image':''},
        {'posn':41, 'card':'2S', 'loci':21 , 'image':''},
        {'posn':42, 'card':'9H', 'loci':21 , 'image':''},
        {'posn':43, 'card':'KS', 'loci':22 , 'image':''},
        {'posn':44, 'card':'6S', 'loci':22 , 'image':''},
        {'posn':45, 'card':'4C', 'loci':23 , 'image':''},
        {'posn':46, 'card':'8H', 'loci':23 , 'image':''},
        {'posn':47, 'card':'9C', 'loci':24 , 'image':''},
        {'posn':48, 'card':'QS', 'loci':24 , 'image':''},
        {'posn':49, 'card':'6D', 'loci':25 , 'image':''},
        {'posn':50, 'card':'QC', 'loci':25 , 'image':''},
        {'posn':51, 'card':'2C', 'loci':26 , 'image':''},
        {'posn':52, 'card':'9D', 'loci':26 , 'image':''},
    ],
    
}

# SAVE STACKS   
json.dump(stacks, open('json_stacks', 'w'))

# %% LOCI

loci = {
    'inandout':[
        {'posn':1,'title':'\"IN\" pillar', 'text':''},
        {'posn':2,'title':'\"OUT\" pillar', 'text':''},
        {'posn':3,'title':'Entrance lamp', 'text':''},
        {'posn':4,'title':'Front door', 'text':''},
        {'posn':5,'title':'Bust of Edward VII', 'text':''},
        {'posn':6,'title':'Nancy Astor portrait', 'text':''},
        {'posn':7,'title':'Brass gun', 'text':''},
        {'posn':8,'title':'Bronze soldier', 'text':''},
        {'posn':9,'title':'Staff reception door', 'text':''},
        {'posn':10,'title':'Main reception', 'text':''},
        {'posn':11,'title':'Postbox', 'text':''},
        {'posn':12,'title':'Lobby pillars', 'text':''},
        {'posn':13,'title':'China vase', 'text':''},
        {'posn':14,'title':'Piano', 'text':''},
        {'posn':15,'title':'Cubby', 'text':''},
        {'posn':16,'title':'Chairmen', 'text':''},
        {'posn':17,'title':'Prince Philip portrait', 'text':''},
        {'posn':18,'title':'Lord Nelson portrait', 'text':''},
        {'posn':19,'title':'Lobby fireplace', 'text':''},
        {'posn':20,'title':'Lobby lamp', 'text':''},
        {'posn':21,'title':'Long bar katana', 'text':''},
        {'posn':22,'title':'Long bar', 'text':''},
        {'posn':23,'title':'Long bar love seat', 'text':''},
        {'posn':24,'title':'Long bar clock & seats', 'text':''},
        {'posn':25,'title':'Long bar desk', 'text':''},  
        {'posn':26,'title':'Portrait of the Queen', 'text':''}, 
        {'posn':27,'title':'Map of S. America', 'text':''}, 
        {'posn':28,'title':'Canning room sofas', 'text':''}, 
        {'posn':29,'title':'Canning room bookshelf', 'text':''}, 
        {'posn':30,'title':'Canning club map', 'text':''},
        {'posn':31,'title':'Courtyard tree', 'text':''}, 
        {'posn':32,'title':'Courtyard double-tree', 'text':''}, 
        {'posn':33,'title':'Courtyard lion fountain', 'text':''}, 
        {'posn':34,'title':'Ballerina', 'text':''}, 
        {'posn':35,'title':'Courtyard pegasus', 'text':''}, 
        {'posn':36,'title':'Goat entrance', 'text':''}, 
        {'posn':37,'title':'Bronze lady', 'text':''}, 
        {'posn':38,'title':'Courtyard tables', 'text':''}, 
        {'posn':39,'title':'Bronze goat', 'text':''}, 
        {'posn':40,'title':'Building supports', 'text':''}, 
        {'posn':41,'title':'Silver Nelson statue', 'text':''}, 
        {'posn':42,'title':'Coffee room door', 'text':''}, 
        {'posn':43,'title':'Club table', 'text':''}, 
        {'posn':44,'title':'Cherub statue 1', 'text':''}, 
        {'posn':45,'title':'Silver horse rider', 'text':''}, 
        {'posn':46,'title':'Coffee room chandelier', 'text':''}, 
        {'posn':47,'title':'Coffee room mirror', 'text':''}, 
        {'posn':48,'title':'Cherub statue 2', 'text':''}, 
        {'posn':49,'title':'Service screen', 'text':''}, 
        {'posn':50,'title':'Coffee room painting', 'text':''}, 
        {'posn':51,'title':'Saving the Colours', 'text':''}, 
        {'posn':52,'title':'Saving the Colours', 'text':''}, 
    ],
}

# SAVE MEMORY PALACES  
json.dump(loci, open('json_loci', 'w'))

# %% GIFS

# These I've taken from giphy
# In a future version of the app we could use the giphy API & call URLs by hashtag
gifs = {    
   'boobs':[{'link':'https://media.giphy.com/media/tGbhyv8Wmi4EM/giphy.gif'},
            {'link':'https://media.giphy.com/media/12WgrmWEDsKN7q/giphy.gif'},
            {'link':'https://media.giphy.com/media/cwHQOWenYfnQA/giphy.gif'},
            {'link':'https://media.giphy.com/media/13746CZnj9zQwo/giphy.gif'},
            {'link':'https://media.giphy.com/media/50cjS4l1tm8ne/giphy.gif'},
            {'link':'https://media.giphy.com/media/PApKgKr6r20mc/giphy.gif'},
            {'link':'https://media.giphy.com/media/7FgtaDSpeuS1q/giphy.gif'},
            {'link':'https://media.giphy.com/media/54Z5yRMdCB2og/giphy.gif'},
            {'link':'https://media.giphy.com/media/fqu8dnXGXkvio/giphy.gif'},
            {'link':'https://media.giphy.com/media/NgLM8pecbMJvq/giphy.gif'},
            {'link':'https://media.giphy.com/media/M8gheIhsLcttS/giphy.gif'},
            {'link':'https://media.giphy.com/media/qW76IdtQdCJPi/giphy.gif'},
            {'link':'https://media.giphy.com/media/50i6YRZxEiqkM/giphy.gif'},
            {'link':'https://media.giphy.com/media/h0yZVLoXKJKb6/giphy.gif'},
            {'link':'https://media.giphy.com/media/rURpGLsAzr4re/giphy.gif'},
            {'link':'https://media.giphy.com/media/e3ju7ALSHtJmM/giphy.gif'},
            {'link':'https://media.giphy.com/media/pYRYdnMICWmti/giphy.gif'},
            {'link':'https://media.giphy.com/media/xuMu0HuHlXiQ8/giphy.gif'},
            {'link':'https://media.giphy.com/media/nZvxbksUffPUI/giphy.gif'},
            {'link':'https://media.giphy.com/media/BIOMe8sws741G/giphy.gif'},
            {'link':'https://media.giphy.com/media/GJttUmwgh5UpG/giphy.gif'},
            {'link':'https://media.giphy.com/media/aZ9thuwFYNjHO/giphy.gif'},
            {'link':'https://media.giphy.com/media/jrD4gAorYjbW/giphy.gif'},
            {'link':'https://media.giphy.com/media/ehlAgT04i9G6c/giphy.gif'},
            {'link':'https://media.giphy.com/media/hq4iYXKfyKMik/giphy.gif'},
            {'link':'https://media.giphy.com/media/eJBAB5D1e7qMM/giphy.gif'},
            {'link':'https://media.giphy.com/media/WvtVUShnvMDn2/giphy.gif'},
            {'link':'https://media.giphy.com/media/pxbEO1EudaSc/giphy.gif'},
            {'link':'https://media.giphy.com/media/6D0dubMvJUtAA/giphy.gif'},
            ],
            
   'strong':[
           {'link':'https://media.giphy.com/media/WrBSHRLE9gEgM/giphy.gif',
            'disc':'Captain America splits log',},
            {'link':'https://media.giphy.com/media/pHXhn8Ee6lRO0KZtM1/giphy.gif',
             'disc':'cartoon hand in a heart'},
            {'link':'https://media.giphy.com/media/20HHkJ3UpFZCt4nQwZ/giphy.gif',
             'disc':'cute kid showing guns'},
            {'link':'https://media.giphy.com/media/xT9Igf2wBfQ8ClCDNC/giphy.gif',
             'disc':'Ali showing fist'},
            {'link':'https://media.giphy.com/media/hV0pccEE0jLfelZPCC/giphy.gif',
             'disc':'cartoon cat lifting weights'},
            {'link':'https://media.giphy.com/media/lPdnkrxkqnS48/giphy.gif',
             'disc':'red panda muscle up'},
            {'link':'https://media.giphy.com/media/cO0dlKKyFGc5q/giphy.gif'},
            {'link':'DC dancing to cakes'},
            {'link':'https://media.giphy.com/media/26FKVSfPIYlZUJngc/giphy.gif'},
            {'link':'cowboy dancing'},
            {'link':'https://media.giphy.com/media/l2JhuG3G56WPngPK0/giphy.gif'},
            {'link':'romero salute'},
            {'link':'https://media.giphy.com/media/5x8am8FstswV2/giphy.gif',
             'disc':'ronda'},
            {'link':'https://media.giphy.com/media/8F32Q0H0L8zyTSCCYI/giphy.gif',
             'disc':'joe rogan commentating'},
            {'link':'https://media.giphy.com/media/aUhEBE0T8XNHa/giphy.gif',
             'disc':'panda dj'},
            {'link':'https://media.giphy.com/media/d1vaWA1lsbIdy/giphy.gif',
             'disc':'kid parks bike'},
            {'link':'https://media.giphy.com/media/Xw6yFn7frR3Y4/giphy.gif',
             'disc':'baby dancing'},
            {'link':'https://media.giphy.com/media/22ZVpCkODW36w/giphy.gif',
             'disc':'DC Dancing with belt'},
             
          ],
             
   'lose':[
           {'link':'https://media.giphy.com/media/127h8dMHnk5H5C/giphy.gif'},
            {'link':'https://media.giphy.com/media/jrmB4IURyv2ik/giphy.gif',
             'disc':'fish face slap'},
            {'link':'https://media.giphy.com/media/3ePb1CHEjfSRhn6r3c/giphy.gif',
             'disc':'loki you had one job'},
            {'link':'https://media.giphy.com/media/NQL7Wuo2JSQSY/giphy.gif',},
            {'link':'https://media.giphy.com/media/PqdfIrXEza6fC/giphy.gif',
             'disc':'yoga kitten crotch bite'},
            {'link':'https://media.giphy.com/media/11StaZ9Lj74oCY/giphy.gif',
             'disc':'penhuin slap'},
            {'link':'https://media.giphy.com/media/47KjwlPVpnQOs/giphy.gif'},
            {'link':'https://media.giphy.com/media/Qc8GJi3L3Jqko/giphy.gif',
             'disc':'sausages to the face'},
            {'link':'https://media.giphy.com/media/fthYZQx5c7hiU/giphy.gif',
             'disc':'archer slap'},
            {'link':'https://media.giphy.com/media/EPcvhM28ER9XW/giphy.gif',
             'disc':'panda smash office'},
            {'link':'https://media.giphy.com/media/vO4ik3XWjkQ2A/giphy.gif',
             'disc':'panda supermarket'},
            {'link':'https://media.giphy.com/media/ZeB4HcMpsyDo4/giphy.gif',
             'disc':'panda falls off log'},
            {'link':'https://media.giphy.com/media/pOeuPPvO3Lbxu/giphy.gif',
             'disc':'panda holding ball'},
            {'link':'https://media.giphy.com/media/47CvsUWHvbmgg/giphy.gif',
             'disc':'panda oh god what have i done'}
          ],            
}
      
# SAVE GIFS
json.dump(gifs, open('json_gifs', 'w'))